CREATE TABLE IF NOT EXISTS clients (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(200) NOT NULL CHECK (length(name) BETWEEN 3 AND 200),
    email VARCHAR(200) UNIQUE
);

CREATE TABLE IF NOT EXISTS planets (
	id VARCHAR(10) PRIMARY KEY CHECK (id ~ '^[A-Z0-9]+$'),
	name VARCHAR(500) NOT NULL UNIQUE CHECK (length(name) BETWEEN 1 AND 500)
);

CREATE TABLE IF NOT EXISTS tickets (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    client_id INTEGER NOT NULL,
    from_planet_id VARCHAR(10) NOT NULL,
    to_planet_id VARCHAR(10) NOT NULL,
    CONSTRAINT fk_client
        FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_planet
        FOREIGN KEY (from_planet_id) REFERENCES planets(id) ON DELETE CASCADE,
        FOREIGN KEY (to_planet_id) REFERENCES planets(id) ON DELETE CASCADE
);